// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

// UPDATE THESE WITH YOUR NETWORK CREDENTIALS
const char DEVICE_LOGIN_NAME[]  = "YOUR_DEVICE_ID";  // Update from Arduino IoT Cloud

const char SSID[]               = "YOUR_WIFI_SSID";     // Network SSID (name)
const char PASS[]               = "YOUR_WIFI_PASSWORD"; // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]         = "YOUR_DEVICE_KEY";    // Secret device password

// Cloud Variables
// These will be synchronized with Arduino IoT Cloud dashboard
float currentTemperature;        // Current temperature reading (READ-ONLY on dashboard)
bool autoControlEnabled;         // Toggle to enable/disable automatic control
bool heaterStatus;               // Current heater status (READ-ONLY on dashboard)
bool manualHeaterControl;        // Manual heater control (when automation disabled)
float tempThresholdLow;          // Lower temperature threshold - heater turns ON below this (18-25°C)
float tempThresholdHigh;         // Upper temperature threshold - heater turns OFF above this (18-25°C)

// Variable callback functions
void onAutoControlEnabledChange();
void onManualHeaterControlChange();
void onTempThresholdLowChange();
void onTempThresholdHighChange();

// WiFi connection for ESP32
WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

// Function to initialize all cloud properties
void initProperties() {
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);

  // Add cloud variables
  ArduinoCloud.addProperty(currentTemperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(autoControlEnabled, READWRITE, ON_CHANGE, onAutoControlEnabledChange);
  ArduinoCloud.addProperty(heaterStatus, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(manualHeaterControl, READWRITE, ON_CHANGE, onManualHeaterControlChange);
  ArduinoCloud.addProperty(tempThresholdLow, READWRITE, ON_CHANGE, onTempThresholdLowChange);
  ArduinoCloud.addProperty(tempThresholdHigh, READWRITE, ON_CHANGE, onTempThresholdHighChange);
}
